name: Java Tests

on:
  pull_request:
    paths:
      - 'src/**'
      - 'test/**'
      - '.github/workflows/java-tests.yml'
  push:
    branches:
      - '**'

jobs:
  student-units-test:
    name: Test Student.getUnits() test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run StudentUnitsTest
        run: mvn -Dtest=StudentUnitsTest test


  print-student-test:
    name: Test Main.printStudent()
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run MainTest
        run: mvn -Dtest=MainTest test
